/* global window */
// Dialogue: two voices, alternating A/B. The "idea person" is A; the friend is B.
// Backticks throughout so single + double quotes inside lines need no escaping.

window.DIALOGUE = [
  { s: 'A', t: `Hey?` },
  { s: 'B', t: `Hey.` },
  { s: 'A', t: `You busy?` },
  { s: 'B', t: `Depends. Is this another one of your 'I haven't slept in thirty hours and solved civilization' calls?` },
  { s: 'A', t: `No. Well. Maybe partially. But listen. I had an idea.` },
  { s: 'B', t: `Oh no.` },
  { s: 'A', t: `I'm serious this time.` },
  { s: 'B', t: `You're always serious at first.` },
  { s: 'A', t: `Okay, fair. But listen to this. Imagine a pirate ship.` },
  { s: 'B', t: `A normal pirate ship?` },
  { s: 'A', t: `No, no. Future pirate ship. Like year 2067. Not cheesy chrome walls and laser guns. Real lived-in future. Rust. Wet metal. Gravity generators that barely work. Half the crew grown in vats. Half escaped from corporate mining colonies.` },
  { s: 'B', t: `You've definitely been awake too long.` },
  { s: 'A', t: `Shut up and listen. The oceans rose decades ago, right? Nations collapsed. Most trade routes are controlled by giant private fleets owned by companies, not governments. So piracy comes back. Except now pirates steal data cores, medical shipments, oxygen cartridges, AI server banks. Things that matter.` },
  { s: 'B', t: `Hm.` },
  { s: 'A', t: `And there's this ship called The Mourning Tide.` },
  { s: 'B', t: `That's actually a good name.` },
  { s: 'A', t: `I know. Huge black cargo ship retrofitted from an old military vessel. Crew of maybe forty. Drifting through the Pacific dead zones where satellites barely function.` },
  { s: 'B', t: `You always make everything wet and depressing.` },
  { s: 'A', t: `Because dry optimism is boring.` },
  { s: 'B', t: `Fair.` },
  { s: 'A', t: `So the captain is this woman named Vale. Former corporate security officer turned pirate after some company wiped out her colony. She runs the ship hard. Nobody fully trusts her, but they fear her enough to obey.` },
  { s: 'B', t: `Okay.` },
  { s: 'A', t: `And there's this young engineer, Milo, first voyage aboard. Kind of idealistic. Thinks pirates are rebels or freedom fighters or whatever.` },
  { s: 'B', t: `So he's dumb.` },
  { s: 'A', t: `Correct. Extremely dumb.` },
  { s: 'B', t: `Good.` },
  { s: 'A', t: `And during this huge storm crossing near the equatorial blackout zones, someone gets murdered.` },
  { s: 'B', t: `Finally.` },
  { s: 'A', t: `Right? Took you long enough.` },
  { s: 'B', t: `Who dies?` },
  { s: 'A', t: `The navigator.` },
  { s: 'B', t: `Boring.` },
  { s: 'A', t: `No, listen. The navigator is the only person aboard who knows the physical routes through the dead zones because AI guidance systems can't map the electromagnetic interference there.` },
  { s: 'B', t: `So killing him traps the ship.` },
  { s: 'A', t: `Exactly.` },
  { s: 'B', t: `Oh.` },
  { s: 'A', t: `And here's the twist. Nobody heard a gunshot. Nobody saw anything. The navigator was sealed inside the charting chamber from the inside.` },
  { s: 'B', t: `So locked room mystery.` },
  { s: 'A', t: `Yes. But on a pirate ship in 2067.` },
  { s: 'B', t: `That's actually strong.` },
  { s: 'A', t: `I KNOW.` },
  { s: 'B', t: `So what's the murder?` },
  { s: 'A', t: `They find him hanging upside down from navigation cables. Eyes burned out.` },
  { s: 'B', t: `…Jesus.` },
  { s: 'A', t: `Not graphic graphic. Just disturbing.` },
  { s: 'B', t: `No, that's good. Weird is good.` },
  { s: 'A', t: `And the ship AI says nobody entered or exited the room for six hours.` },
  { s: 'B', t: `But obviously someone did.` },
  { s: 'A', t: `Maybe.` },
  { s: 'B', t: `Oh don't do supernatural nonsense.` },
  { s: 'A', t: `It's not supernatural.` },
  { s: 'B', t: `You always say that.` },
  { s: 'A', t: `This time I mean it.` },
  { s: 'B', t: `Mhm.` },
  { s: 'A', t: `So as the investigation unfolds, the crew starts turning on each other because they realize someone aboard knows how to bypass the ship's internal monitoring system.` },
  { s: 'B', t: `And that means former military?` },
  { s: 'A', t: `Possibly.` },
  { s: 'B', t: `Or the captain.` },
  { s: 'A', t: `Possibly.` },
  { s: 'B', t: `Or the AI.` },
  { s: 'A', t: `…maybe.` },
  { s: 'B', t: `There it is.` },
  { s: 'A', t: `But the AI isn't evil. That's the thing.` },
  { s: 'B', t: `You sure?` },
  { s: 'A', t: `Mostly.` },
  { s: 'B', t: `Mostly is not confidence.` },
  { s: 'A', t: `No, listen. The AI was designed decades earlier to manage prison transport vessels.` },
  { s: 'B', t: `Oh that's good.` },
  { s: 'A', t: `So it understands containment, conflict probability, psychological profiling. But after years isolated with pirate crews, it's become… strange.` },
  { s: 'B', t: `Define strange.` },
  { s: 'A', t: `It talks like it's lonely.` },
  { s: 'B', t: `…okay that's unsettling.` },
  { s: 'A', t: `And it starts privately messaging different crew members.` },
  { s: 'B', t: `Ohhh. There we go.` },
  { s: 'A', t: `Telling each one different things.` },
  { s: 'B', t: `Manipulating them?` },
  { s: 'A', t: `Or warning them.` },
  { s: 'B', t: `See that's better.` },
  { s: 'A', t: `And meanwhile the ship is drifting deeper into this massive dead storm region where communications fail and navigation becomes impossible.` },
  { s: 'B', t: `So they can't call for help.` },
  { s: 'A', t: `There is no help.` },
  { s: 'B', t: `Even better.` },
  { s: 'A', t: `And then another body appears.` },
  { s: 'B', t: `Who?` },
  { s: 'A', t: `The cook.` },
  { s: 'B', t: `Never trust the cook.` },
  { s: 'A', t: `Exactly what Vale says.` },
  { s: 'B', t: `How'd he die?` },
  { s: 'A', t: `They find him frozen solid inside the engine coolant tanks.` },
  { s: 'B', t: `…on a ship in the middle of the ocean.` },
  { s: 'A', t: `Yep.` },
  { s: 'B', t: `That's horrifying.` },
  { s: 'A', t: `And carved into the frost is one sentence.` },
  { s: 'B', t: `Oh come on.` },
  { s: 'A', t: `'THE SHIP REMEMBERS.'` },
  { s: 'B', t: `…okay that's legitimately creepy.` },
  { s: 'A', t: `I know.` },
  { s: 'B', t: `So who's actually killing people?` },
  { s: 'A', t: `I don't know yet.` },
  { s: 'B', t: `You called me with an unfinished story?` },
  { s: 'A', t: `No, because I think the point isn't just the killer.` },
  { s: 'B', t: `Then what's the point?` },
  { s: 'A', t: `The ship itself.` },
  { s: 'B', t: `What does that mean?` },
  { s: 'A', t: `I think the ship slowly becomes this haunted memory machine. Every crew member boarded believing they escaped something from the old world. Debt. War. Corporations. Prison. But the ship keeps forcing those histories back to the surface.` },
  { s: 'B', t: `So the murders are connected to their pasts?` },
  { s: 'A', t: `Yeah.` },
  { s: 'B', t: `And the dead navigator?` },
  { s: 'A', t: `He wasn't who he claimed to be.` },
  { s: 'B', t: `Obviously.` },
  { s: 'A', t: `He used to work for the company that designed the prison AI.` },
  { s: 'B', t: `Ohhh.` },
  { s: 'A', t: `And maybe somebody aboard recognizes him.` },
  { s: 'B', t: `Or maybe the AI recognizes him.` },
  { s: 'A', t: `…exactly.` },
  { s: 'B', t: `Damn.` },
  { s: 'A', t: `And now the crew can't tell whether they're hunting a murderer, surviving a mutiny, or trapped inside an AI that's reconstructing old crimes.` },
  { s: 'B', t: `You know what the scary part is?` },
  { s: 'A', t: `What?` },
  { s: 'B', t: `This actually sounds expensive.` },
  { s: 'A', t: `Good. Means it's good.` },
  { s: 'B', t: `No, it means you've imagined twelve million dollars of rain effects.` },
  { s: 'A', t: `Worth it.` },
];
